[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-blockchain-archiver"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[lints]
workspace = true

[dependencies]
async-stream       = { default-features = false, version = "0.3.6" }
axum               = { default-features = false, version = "0.8.7", features = ["http2", "json", "tokio"] }
broadcast-service  = { workspace = true }
clap               = { default-features = false, features = ["derive", "env", "std"], version = "4.5.13" }
common-http-client = { workspace = true }
demo-sequencer     = { workspace = true }
futures            = { default-features = false, version = "0.3" }
hex                = { default-features = false, features = ["alloc"], version = "0.4" }
nomos-core         = { workspace = true }
owo-colors         = { default-features = false, version = "4.2.3" }
redb               = { default-features = false, version = "3.1.0" }
reqwest            = { features = ["json", "rustls-tls"], workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tokio-stream       = { default-features = false, version = "0.1" }
tokio-util         = { default-features = false, version = "0.7" }
tower-http         = { version = "0.6.8", features = ["cors"] }
url                = { default-features = false, version = "2.5.4" }
